### ISSUE TITLE
Docs support C++11, makefile does not

### ISSUE THREAD

**Issue by OJFord** [m8pple/arch2-2014-cw1#13]
Since https://github.com/m8pple/arch2-2014-cw1/issues/4, it is [specified that](https://github.com/OJFord/MIPSim#compilation-environment) the compilation environment is C99 or C++11.

However, the makefile has not been updated to reflect this.

[Suggested fix](https://github.com/m8pple/arch2-2014-cw1/pull/14) is to add `CXXFLAGS += -std=c++11` (and relatedly, `CFLAGS += -std=c99`).

**Comment by m8pple** [comment]
I managed to mess up the commit message, but fixed due to pull. Thanks.
