### ISSUE TITLE
Bug: '<internal>' tests will always generate warning

### ISSUE THREAD

**Issue by OJFord** [m8pple/arch2-2014-cw1#15]
In [the test framework](https://github.com/m8pple/arch2-2014-cw1/blob/master/src/shared/mips_test_framework.cpp#L125), the instruction name on test is converted to upper case prior to searching the set of known instructions.

As such, any test of `"<internal>"` (or `"<INTERNAL>"`) will render the warning:

```
Warning:mips_test_begin_test - Unknown instruction '<INTERNAL>', might want to check the spelling.
```

to `stderr`.

Suggested fix is to change [the `*instr_info_t.instruction`](https://github.com/m8pple/arch2-2014-cw1/blob/master/src/shared/mips_test_framework.cpp#L36) to `"<INTERNAL>"`; maintaining case-insensitivity.

**Comment by m8pple** [comment]
Pull accepted. I managed not to move an earlier fix from my private repository
over to the public one. What I get for out of tree testing.
