### ISSUE TITLE
Ambiguity due to 'off-spec' instructions

### ISSUE THREAD

**Issue by OJFord** [m8pple/arch2-2014-cw1#16]
As per the readme and #1, not all instructions in the MIPS-I specification are part of this spec.

Does that mean that those MIPS-I instructions not covered here should raise a `mips_ExceptionInvalidInstruction`, or are they valid instructions that have undefined behaviour?

**Comment by m8pple** [comment]
They are valid instructions with implementation defined behaviour. I'll update the spec.
