### ISSUE TITLE
Is mips_mem_ram "an" or "the" implementation?

### ISSUE THREAD

**Issue by OJFord** [m8pple/arch2-2014-cw1#20]
Are we allowed to use our own memory structures, or is it required that we use [mips_mem_ram](https://github.com/m8pple/arch2-2014-cw1/blob/master/src/shared/mips_mem_ram.cpp#L1) to implement the memory provider?

If allowed, (as I had thought), the makefile needs to not link against the precompiled objects, and I think a mutual `#define` directive would need to be used, and checked for in `shared/mips_mem_ram.cpp` processed _after_ `src/$(LOGIN)`?

**Comment by m8pple** [comment]
I hadn't anticipated people wanting to use their own memory when their
tester runs (though I see the benefit), so there is no mechanism to
communicate it.

Currently my test of your tester also uses a different RAM implementation,
so it would break my harnesses.

So implementing mips_mem_create_ram etc. is not allowed - the version
in shared is an example for testing, but in the assessment environment
no assumptions can be made.
