### ISSUE TITLE
Testing compiler versions

### ISSUE THREAD

**Issue by p--b** [m8pple/arch2-2014-cw1#5]
It would be really helpful if a minimum version of the compiler against which the code will be tested could be indicated - even if code is compliant with a given standard, it may not compile on a given compiler given that there are many incomplete implementations in current use.

**Comment by OJFord** [comment]
Seconded - on Mac you can be blind-sided be auto-inclusion of some (semi- and) standard libraries, even outside of Xcode with "command line tools". `-Wall` may mention it though, not sure.
