### ISSUE TITLE
PC initialisation in reset condition ambiguity

### ISSUE THREAD

**Issue by p--b** [m8pple/arch2-2014-cw1#9]
An ambiguity appears to exist with respect to the initialisation of the PC on reset. There doesn't seem to be any defined function that requires this to occur, despite the documentation for `mips_cpu_reset(mips_cpu_h)` and `mips_cpu_create(mips_mem_h)` implying that creation/reset is analogous to assertion of the CPU's reset input.

The documentation simply states that the CPU should be left with `all registers zerod`, however, as the PC is not a register, zeroing of the PC does not appear to be explicitly required, despite this action being implied by the description.

A fix would be to include `and the PC initialised to zero` after `all registers zerod` in the description of `mips_cpu_reset` and after `all registers set to zero` in `mips_cpu_create`.

**Comment by m8pple** [comment]
The PC is a kind of register, as it is a stateful part of the hardware (and there are others beyond the 32 general purpose regs and the PC), so this only requires thinking about the underlying hardware.

There _is_ an ambiguity with respect to at least one of the registers, but that is already highlighted elsewhere in the documentation.
